destination: ./_site
auto:        true
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   date
paginate: 5
excerpt_separator: <!-- more -->
rdiscount:
  extensions: [smart]
redcarpet:
  extensions: [fenced_code_blocks]
  render_options:
